version: "3.7"

networks:
  py-shorten-url:
    name: py-shorten-url
    driver: bridge

volumes:
  mysql-volume:

services:
  py-shorten-url:
    build:
      context: ../
      dockerfile: ./build/dockerfile
    image: py-shorten-url:dev
    container_name: py-shorten-url
    volumes:
      - type: bind
        source: ../
        target: /app/
    working_dir: /app
    restart: "always"
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - py-shorten-url
    env_file:
      - ../configs/dev.env
    tty: true

    logging:
      driver: json-file

  mysql:
    image: mysql:8
    container_name: py-shorten-url-mysql
    ports:
      - 127.0.0.1:3306:3306
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: q
      MYSQL_DATABASE: shorten_url
      MYSQL_USER: shorten_url
      MYSQL_PASSWORD: q
    restart: "always"
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - py-shorten-url

  redis:
    image: redis:6
    container_name: py-shorten-url-redis
    ports:
      - 127.0.0.1:6379:6379
    tty: true
    restart: "always"
    networks:
      - py-shorten-url
